add specific packages for raspberry pi
k8s-at-home/template-cluster-k3s pull request #180
Opened 2022-01-01 18:56 UTC by c-yco

**Description of the change**

Add two tasks to determine if the role is running on a raspberry pi and install raspi specific packages.
Currently only package linux-modules-extra-raspi

**Benefits**

Calico pods will start successfully. Without the package the pods had periodic sigvaults every 30 secs. All other pods coulnt be deployed

**Possible drawbacks**

Only tested on raspi 4

2022-01-01 19:13 UTC, onedr0p requested changes

2022-01-01 19:13 UTC, onedr0p commented on provision/ansible/roles/ubuntu/tasks/packages.yml
> +  register: is_raspberry
```suggestion
- name: Check if Raspberry Pi
  command: grep -q  "Raspberry Pi" /proc/cpuinfo
  ignore_errors: true
  register: is_raspberry 
```

2022-01-01 21:18 UTC, samip5 commented
I'm going to chime in here, that that will result in error with packages on a Raspberry Pi's running Ubuntu.

```
$ apt policy linux-mdoules-extra-raspi
N: Unable to locate package linux-mdoules-extra-raspi
```

2022-01-01 21:27 UTC, c-yco commented
Will add another condition to only run on 21.01 tomorrow

2022-01-01 22:43 UTC, onedr0p commented
Maybe it would also be needed in 22.04?

2022-01-02 10:53 UTC, c-yco commented
I added a condition to install only on 21 or greater, so this should also work then for 22.04 when it comes out

2022-01-02 11:48 UTC, onedr0p approved these changes

2022-01-02 11:48 UTC, merged

2022-05-01 12:15 UTC, onedr0p commented
@c-yco see https://github.com/k8s-at-home/template-cluster-k3s/issues/251 this might need touching up. For now I have removed the logic.